# Generated by Django 4.2 on 2023-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я/Нік")),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Повідомлення')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Опубліковано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показано')),
            ],
        ),
    ]
