# Generated by Django 4.2 on 2023-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['email', 'time_create', 'is_published'], 'verbose_name': "Зворотній зв'язок"},
        ),
        migrations.AddField(
            model_name='feedback',
            name='captcha',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
